version: "3.9"

services:
  backend:
    container_name: base-ts-vite
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: local
    ports:
      - 3000:3000
    volumes:
      - ./:/server
    command: > 
      sh -c "yarn install && yarn dev"
